### ISSUE TITLE
Hi. Please add my projects

### ISSUE THREAD

**Issue by Competitions-Champville** [iea/rpi-competition-index#1]
https://github.com/Competitions-Champville/MedHelper

https://github.com/Competitions-Champville/SEMS

Thank you.

George ASMAR

**Comment by omaraboumrad** [comment]
Hello George,

Please don't forget to add your project's source code to both repositories as well.

**Comment by omaraboumrad** [comment]
Good Job Champville.

**Comment by Competitions-Champville** [comment]
Please confirm good reception of all my projects. Thank you.
George Asmar

**Comment by omaraboumrad** [comment]
Hi George,

You're supposed to upload the video to YouTube and post a link on the IEA Platform. GitHub is only for source code. After you've done so please proceed with the following:

For SMES: Delete SMES.mp4
For MedHelper: Delete MedHelper.zip and MedHelper.mp4 and only push the 4 files in your zip archive.
