### ISSUE TITLE
Please add my project 

### ISSUE THREAD

**Issue by mmaasrani** [iea/rpi-competition-index#13]
Https://github.com/mmaasrani/Tripoli-from-a-dream-to-reality

**Comment by omaraboumrad** [comment]
Good Job MMaasrani. Which school is this?

Good luck!

**Comment by mmaasrani** [comment]
AZM school from tripoli

**Comment by mmaasrani** [comment]
Thank Mr. Omar . It is AZM school from tripoli.

Sent from my Samsung device

-------- Original message --------
