### ISSUE TITLE
Smart School

### ISSUE THREAD

**Issue by kamelnazar** [iea/rpi-competition-index#14]
Programming in all societies helps people by solving their problems at school, house, city and village. The schools in Lebanon face many problems (Electrical, Cultural, Environmental…); sometimes, we need programming language to build an application to solve them.
So, this application can help schools in Lebanon to be more developed and up to date… in many domains.

**Comment by omaraboumrad** [comment]
kamelnazar,

We need the link to your project that was pushed to GitHub.

**Comment by alhadi-team** [comment]
alhadi-team/-لو سمحت  اضف مؤسسة الهادي

**Comment by alhadi-team** [comment]
https://github.com/alhadi-team/-.git

**Comment by omaraboumrad** [comment]
Good job Alhadi,

Good luck!

Please rename README.md to code.py

1) open README.md
2) Click on the Pencil icon to Edit
3) in the box that says README.md, rename it to: code.py
4) When done click the green button below.

**Comment by kamelnazar** [comment]
http://github.com/kamelnazar/smart-school
