### ISSUE TITLE
Please add my project

### ISSUE THREAD

**Issue by Christinanakhle** [iea/rpi-competition-index#4]
https://github.com/Christinanakhle/Garbaginator.git

**Comment by Christinanakhle** [comment]
Hello Omar,

I have attached our first project from Brummana High School. 
Can you please confirm if all is ok? 
Thank you

Christina Nakhle

**Comment by omaraboumrad** [comment]
Dear Christina,

Please push the content of the zip file only (in your case, the folder containing the python files, or the python files themselves) and then delete the Zip file.

**Comment by Christinanakhle** [comment]
Ok done

Thank you

**Comment by omaraboumrad** [comment]
Thanks Christina and Good job Brummana High School.

Good luck!
