### ISSUE TITLE
please add my project

### ISSUE THREAD

**Issue by HassanEzz** [iea/rpi-competition-index#5]
https://github.com/mariamfakihh/Raspberry-pi-project-for-blinds

**Comment by omaraboumrad** [comment]
Good job Tyre Secondary School.

Good luck!

**Comment by HassanEzz** [comment]
Thank you
Best,
Mariam

Sent from my Sony Xperia™ smartphone

---- Omar Abou Mrad wrote ----

Closed #5https://github.com/iea/rpi-competition-index/issues/5.

**Comment by smartbelt** [comment]
https://github.com/smartbelt/lyceeofficielhammana.git
