### ISSUE TITLE
Please add my project

### ISSUE THREAD

**Issue by AssaadFeghali** [iea/rpi-competition-index#7]
https://github.com/AssaadFeghali/RaspberyPi

**Comment by GHobeiry1** [comment]
https://github.com/GHobeiry1/smart-trash-basket

**Comment by omaraboumrad** [comment]
Good job to both.

Good Luck!

**Comment by AssaadFeghali** [comment]
Thank You

**Comment by omaraboumrad** [comment]
Assaad which school does this project belong to?

**Comment by AssaadFeghali** [comment]
Antonine International School
