### ISSUE TITLE
please add my project

### ISSUE THREAD

**Issue by 7acs2016** [iea/rpi-competition-index#8]
Please add my project

**Comment by omaraboumrad** [comment]
Hello,

Please upload the python code file separately.

**Comment by 7acs2016** [comment]
where

**Comment by 7acs2016** [comment]
I did

**Comment by 7acs2016** [comment]
but im not knowing how to send request to iea

**Comment by omaraboumrad** [comment]
Your request is received, now you need to fix the following:

1) Open the following: https://github.com/7acs2016/pi-code/blob/master/README.md
2) Click on the Pencil icon to Edit
3) in the box that says `README.md`, rename it to: `code.py`
4) When done click the green button below.

When done, please reply here and mention the name of your school.

Thanks

**Comment by 7acs2016** [comment]
thx

**Comment by 7acs2016** [comment]
I did

**Comment by 7acs2016** [comment]
now

**Comment by 7acs2016** [comment]
we also wanted you to edit the grade 8 acs project made by the account :
8acs2016

**Comment by eliasazzam** [comment]
https://github.com/eliasazzam/TGH i have this URL but i don't know where to put it

**Comment by omaraboumrad** [comment]
Good job ACS, both projects added to the index.

Good Luck!

## 

Elias Azzam,

Please follow these steps:

1) Open the following: https://github.com/eliasazzam/TGH/blob/master/README.md
2) Click on the Pencil icon to Edit
3) in the box that says README.md, rename it to: code.py
4) When done click the green button below.

When done, please reply here and mention the name of your school.

Thanks

**Comment by eliasazzam** [comment]
I have done the steps.
Name of the school:
Official secondary school for girls zahle

**Comment by omaraboumrad** [comment]
Good job Official Secondary School Zahle!

Good luck!

**Comment by eliasazzam** [comment]
I have done the steps for another project TPG.
Official secondary school for girls zahle
